### ISSUE TITLE
Image error handler

### ISSUE THREAD

**Issue by DevCilla** [vvvmax/unitegallery#23]
Hi, as the images shown in my gallery are randomly get from the Internet, are there any error handlers once the image is not exists?
I tried the `onerror` attribute was not working in this case

```
<img src="http://somewhere-thumb.jpg" data-image="http://somewhere-large.jpg" onerror="this.src='/images/noimage.jpg'">
```

**Comment by vvvmax** [comment]
Hinnthere is no onerrir. Sorry. They are just not shown. You mean for
thumbs or for big images?

**Comment by pokemonTrainee** [comment]
for the large image, thanks

**Comment by vvvmax** [comment]
For the big images I don't have event. they just don't show. But it's a
good idea. I'll add it to my new features list.

**Comment by pokemonTrainee** [comment]
Thanks for your consideration! look forward to new features :)

**Comment by skitterm** [comment]
I'm seeing a similar issue -- I'm using the tiles-justified layout. 

Here's my gallery with the images:
![gallery](https://cloud.githubusercontent.com/assets/5875149/22351587/8db4ec50-e3cd-11e6-82eb-c729ff067651.JPG)

But if one of the images doesn't load, the gallery doesn't render as it should -- instead, it collapses and all the images are stacked on top of each other, and they all have the same height and width:
![images](https://cloud.githubusercontent.com/assets/5875149/22351638/b6e3d370-e3cd-11e6-9d84-376fe4bd5bc0.JPG)

In this case, the images are somehow all getting set to `top: 0` with no `left` style set.

It's really crucial that the gallery still renders even if an image doesn't load. My app allows users to create image galleries and we have no control over where/how their images are hosted. With the web, there's no guarantee that an image available now will be available later. But if the gallery doesn't render correctly when an image is gone, it breaks the whole experience.

 Some ideas:
* At the least, could the gallery could ignore the broken image and just load the other images? 
* At best, what if there was a dimensions property so the images' dimensions could be entered in the HTML, so that even if an image didn't load, its dimensions were still known?
* If that's not possible, could there be some way to hook into an "on image error" event so I could choose how to handle the broken image?

**Comment by vvvmax** [comment]
HI, I'll think about that. I need to rewrite a little the justified type
algoritm so it will work even if some image is brocken. also, I need to
make it work with the dimentions like you mentioned so it will load faster
and not when all the images are loaded.

I"m working slow and it could take time. so while I do it you can use tiles
columns instead if it's good for your app.



On Thu, Jan 26, 2017 at 11:56 PM, Steven Kitterman <notifications@github.com

**Comment by skitterm** [comment]
Here was my workaround -- not sure it's foolproof enough for a PR, but in case it helps:
In the function
`this.getImageOriginalSize`, 
I changed 
`if(typeof htmlImage.naturalWidth == "undefined")`
to be 
`if(typeof htmlImage.naturalWidth == "undefined" || (htmlImage.naturalWidth === 0 && htmlImage.naturalHeight === 0)){`

So it catches an image that "doesn't show".

Then instead of making the image's dimensions
`return({width:0, height:0});`, 
I grabbed the backup dimensions from the DOM, where I had stored them as a data-attribute:
`return({width:objImage.data('backupWidth'),height:objImage.data('backupHeight')});`

An even better idea than that might be to pass the backup dimensions into the `getImageOriginalSize` function itself, directly from the `objItem`.

**Comment by vvvmax** [comment]
HI, if the image is not loaded it should be just ignored I think rather
then adding it to the list with some "hole". I'll think about something.

**Comment by SDaron** [comment]
I have the same issue, occuring randomly. I can't find the reason explaining that one of the images was not correctly loaded but then the gallery shows all images on the same place.
