### ISSUE TITLE
Open a Lightbox oder Video-item from outside the gallery

### ISSUE THREAD

**Issue by skerbis** [vvvmax/unitegallery#96]
How is it possible
I use a overlay to show some more Information about a Video. I need there a link to open the corrsespnding Video from the gallery (justified). Is it possible to open the (Video)Video oder the Lightbox-Item from outside the Gallery?

**Comment by vvvmax** [comment]
HI. it's not posible in the gallery. only if you start playing youtube and
press on the "show on youtube" button (same with vimeo) .

**Comment by skerbis** [comment]
I mean can i trigger / click / open an Item from outside the gallery using an action or something like that?

**Comment by vvvmax** [comment]
HI, still don't understand. What you mean? You want to show image when go
to page?

**Comment by skerbis** [comment]
http://2016.schemmann.com/ click please on about, this opens an Info.  Inside the info i would like to have a button to open the file/slide.

**Comment by vvvmax** [comment]
HI, I see you done this:

http://screencast.com/t/6yBGatdf2vB

you mean that if you click the bottom text some other box will appear?
something like this?

If I right (I am not sure that I totally understand you) then it would
involve to edit some core js files, because I didn't made this option
available. There is a description but you can view it only as part of the
lightbox.
